# Definindo as funÃ§Ãµes que vamos usar

In [1]:
def get_params_acc (mat):
    
    items_1 = mat.split('_')
    items_2 = items_1[len(items_1) - 1].split('.')
    items_2 = items_2[len(items_2) - 2]
    items_1 = items_1[:len(items_1) - 1]
    items = items_1 + [items_2]
    items = [int(y) for y in items]
    
    file = items[0]
    date = datetime.strptime(str(items[1]), '%Y%m%d')
    root_index = items[2]
    daily_passing = items[3]
    region = items[4]
    direction = items[5]
    sensor_num = items[6]
    
    return date, daily_passing, region, direction, sensor_num

def get_params_gps (mat):
    
    items_1 = mat.split('_')
    items_2 = items_1[len(items_1) - 1].split('.')
    items_2 = items_2[0][:1]
    items_1 = items_1[:len(items_1) - 1]
    items = items_1 + [items_2[0]]
    items = [int(y) for y in items]
    
    file = items[0]
    date = datetime.strptime(str(items[1]), '%Y%m%d')
    root_index = items[2]
    daily_passing = items[3]
    region = items[4]
    direction = items[5]
    
    return date, daily_passing, region, direction



def load_Data_Frame_acc (num_train, region_given, DateStart, DateEnd):
    
    df_date = pd.DataFrame()
    df_daily = pd.DataFrame()
    df_region = pd.DataFrame()
    df_direction = pd.DataFrame()
    df_trix = pd.DataFrame()
    df_triy = pd.DataFrame()
    df_triz = pd.DataFrame()
    df_front = pd.DataFrame()
    df_back = pd.DataFrame()
    df_1 = pd.DataFrame()
    df_2 = pd.DataFrame()
    df_acc = pd.DataFrame()
    
    
    if num_train == 4306:
        for mat in os.listdir(dataDir[0]):
            result = get_params_acc(mat)
            
            date = result[0]
            daily_passing = result[1]
            region = result[2]
            direction = result[3]
            sensor_num = result[4]
            
            if region == region_given and date >= DateStart and date <= DateEnd:
                
                try:
                    acc_1 = scipy.io.loadmat(dataDir[0]+mat)
                    
                    df_date = pd.DataFrame(data = [date], columns = ['Date'])
                    df_daily = pd.DataFrame(data = [daily_passing], columns = ['Daily_passing'])
                    df_region = pd.DataFrame(data = [region], columns = ['Region'])
                    df_direction = pd.DataFrame(data = [direction], columns = ['Direction'])
                    
                    if sensor_num == 1:
                        df_trix = pd.DataFrame(data = acc_1['save_var'], columns = ['Triaxial_x'])
                        
                    elif sensor_num == 2:
                        df_triy = pd.DataFrame(data = acc_1['save_var'], columns = ['Triaxial_y'])
                        
                    elif sensor_num == 3:
                        df_triz = pd.DataFrame(data = acc_1['save_var'], columns = ['Triaxial_z'])
                    
                    elif sensor_num == 4:
                        df_front = pd.DataFrame(data = acc_1['save_var'], columns = ['Front_cab_uni'])
                        
                    elif sensor_num == 5:
                        df_back = pd.DataFrame(data = acc_1['save_var'], columns = ['Back_cab_uni'])
                        
                        
                    df_1 = pd.concat([df_date, df_daily, df_region, df_direction, 
                                      df_trix, df_triy, df_triz, df_front, df_back], axis = 1)
        
                except:
                    acc_1 = h5py.File(dataDir[0]+mat, 'r').get('save_var')

                    df_date = pd.DataFrame(data = [date], columns = ['Date'])
                    df_daily = pd.DataFrame(data = [daily_passing], columns = ['Daily_passing'])
                    df_region = pd.DataFrame(data = [region], columns = ['Region'])
                    df_direction = pd.DataFrame(data = [direction], columns = ['Direction'])
                    
                    if sensor_num == 1:
                        df_trix = pd.DataFrame(data = np.array(acc_1).reshape(-1,1), columns = ['Triaxial_x'])
                        
                    elif sensor_num == 2:
                        df_triy = pd.DataFrame(data = np.array(acc_1).reshape(-1,1), columns = ['Triaxial_y'])
                        
                    elif sensor_num == 3:
                        df_triz = pd.DataFrame(data = np.array(acc_1).reshape(-1,1), columns = ['Triaxial_z'])
                    
                    elif sensor_num == 4:
                        df_front = pd.DataFrame(data = np.array(acc_1).reshape(-1,1), columns = ['Front_cab_uni'])
                        
                    elif sensor_num == 5:
                        df_back = pd.DataFrame(data = np.array(acc_1).reshape(-1,1), columns = ['Back_cab_uni'])
                        
                    df_2 = pd.concat([df_date, df_daily, df_region, df_direction, 
                                      df_trix, df_triy, df_triz, df_front, df_back], axis = 1)
        

                df_acc = pd.concat([df_1, df_2], axis = 0, ignore_index = True)
            
                df_acc = df_acc.fillna(method = 'ffill')
                
                li_acc.append(df_acc)
                
        
        df_acc = pd.concat(li_acc, axis = 0, ignore_index = True)
        
        return df_acc

    elif num_train == 4313:
        for mat in os.listdir(dataDir[2]):
            result = get_params_acc(mat)
            
            date = result[0]
            daily_passing = result[1]
            region = result[2]
            direction = result[3]
            sensor_num = result[4]
            
            if region == region_given and date >= DateStart and date <= DateEnd:
                
                try:
                    acc_1 = scipy.io.loadmat(dataDir[2]+mat)
                    
                    df_date = pd.DataFrame(data = [date], columns = ['Date'])
                    df_daily = pd.DataFrame(data = [daily_passing], columns = ['Daily_passing'])
                    df_region = pd.DataFrame(data = [region], columns = ['Region'])
                    df_direction = pd.DataFrame(data = [direction], columns = ['Direction'])
                    
                    if sensor_num == 1:
                        df_trix = pd.DataFrame(data = acc_1['save_var'], columns = ['Triaxial_x'])
                        
                    elif sensor_num == 2:
                        df_triy = pd.DataFrame(data = acc_1['save_var'], columns = ['Triaxial_y'])
                        
                    elif sensor_num == 3:
                        df_triz = pd.DataFrame(data = acc_1['save_var'], columns = ['Triaxial_z'])
                    
                    elif sensor_num == 4:
                        df_front = pd.DataFrame(data = acc_1['save_var'], columns = ['Front_cab_uni'])
                        
                    elif sensor_num == 5:
                        df_back = pd.DataFrame(data = acc_1['save_var'], columns = ['Back_cab_uni'])
                        
                        
                    df_1 = pd.concat([df_date, df_daily, df_region, df_direction, 
                                      df_trix, df_triy, df_triz, df_front, df_back], axis = 1)
        
                except:
                    acc_1 = h5py.File(dataDir[0]+mat, 'r').get('save_var')

                    df_date = pd.DataFrame(data = [date], columns = ['Date'])
                    df_daily = pd.DataFrame(data = [daily_passing], columns = ['Daily_passing'])
                    df_region = pd.DataFrame(data = [region], columns = ['Region'])
                    df_direction = pd.DataFrame(data = [direction], columns = ['Direction'])
                    
                    if sensor_num == 1:
                        df_trix = pd.DataFrame(data = np.array(acc_1).reshape(-1,1), columns = ['Triaxial_x'])
                        
                    elif sensor_num == 2:
                        df_triy = pd.DataFrame(data = np.array(acc_1).reshape(-1,1), columns = ['Triaxial_y'])
                        
                    elif sensor_num == 3:
                        df_triz = pd.DataFrame(data = np.array(acc_1).reshape(-1,1), columns = ['Triaxial_z'])
                    
                    elif sensor_num == 4:
                        df_front = pd.DataFrame(data = np.array(acc_1).reshape(-1,1), columns = ['Front_cab_uni'])
                        
                    elif sensor_num == 5:
                        df_back = pd.DataFrame(data = np.array(acc_1).reshape(-1,1), columns = ['Back_cab_uni'])
                        
                    df_2 = pd.concat([df_date, df_daily, df_region, df_direction, 
                                      df_trix, df_triy, df_triz, df_front, df_back], axis = 1)
        

                df_acc = pd.concat([df_1, df_2], axis = 0, ignore_index = True)
            
                df_acc = df_acc.fillna(method = 'ffill')
                
                li_acc.append(df_acc)
                
        
        df_acc = pd.concat(li_acc, axis = 0, ignore_index = True)
        
        return df_acc    
    
    
def load_Data_Frame_gps (num_train, region_given, DateStart, DateEnd):

    df_date = pd.DataFrame()
    df_daily = pd.DataFrame()
    df_region = pd.DataFrame()
    df_direction = pd.DataFrame()
    df_aux = pd.DataFrame()
    df_gps = pd.DataFrame()
    
    
    if num_train == 4306:
        for mat in os.listdir(dataDir[1]):
            result = get_params_gps(mat)
            
            date = result[0]
            daily_passing = result[1]
            region = result[2]
            direction = result[3]
            
            if region == region_given and date >= DateStart and date <= DateEnd:
            
                gps_1 = scipy.io.loadmat(dataDir[1]+mat)
                
                df_date = pd.DataFrame(data = [date], columns = ['Date'])
                df_daily = pd.DataFrame(data = [daily_passing], columns = ['Daily_passing'])
                df_region = pd.DataFrame(data = [region], columns = ['Region'])
                df_direction = pd.DataFrame(data = [direction], columns = ['Direction'])
                
                df_aux = pd.DataFrame(data = gps_1['save_var_gps'], columns = ['Longitude', 'Latitude', 'Altitude', 'Velocidade', 'TimeStamp'])
    
                df_gps = pd.concat([df_date, df_daily, df_region, df_direction, df_aux], axis = 1)
        
                df_gps = df_gps.fillna(method = 'ffill')
            
                li_gps.append(df_gps)
                
        
        df_gps = pd.concat(li_gps, axis = 0, ignore_index = True)
        
        return df_gps
    
    
    elif num_train == 4313:
        for mat in os.listdir(dataDir[3]):
            result = get_params_gps(mat)
            
            date = result[0]
            daily_passing = result[1]
            region = result[2]
            direction = result[3]
            
            if region == region_given and date >= DateStart and date <= DateEnd:
            
                gps_1 = scipy.io.loadmat(dataDir[3]+mat)
                
                df_date = pd.DataFrame(data = [date], columns = ['Date'])
                df_daily = pd.DataFrame(data = [daily_passing], columns = ['Daily_passing'])
                df_region = pd.DataFrame(data = [region], columns = ['Region'])
                df_direction = pd.DataFrame(data = [direction], columns = ['Direction'])
                
                df_aux = pd.DataFrame(data = gps_1['save_var_gps'], columns = ['Longitude', 'Latitude', 'Altitude', 'Velocidade', 'TimeStamp'])
    
                df_gps = pd.concat([df_date, df_daily, df_region, df_direction, df_aux], axis = 1)
        
                df_gps = df_gps.fillna(method = 'ffill')
            
                li_gps.append(df_gps)
                
        
        df_gps = pd.concat(li_gps, axis = 0, ignore_index = True)
        
        return df_gps

In [2]:
import h5py
import scipy.io
import os
import pandas as pd
import numpy as np
from datetime import datetime

## Dfinindo path

In [3]:
dataDir = ['D:/DR_train/DR_Train/LRV4306/accelerometer_data/', 'D:/DR_train/DR_Train/LRV4306/gps_data/',
           'D:/DR_train/DR_Train/LRV4313/accelerometer_data/', 'D:/DR_train/DR_Train/LRV4313/gps_data/']

li_acc = []
li_gps =[]

## Definindo data de comeÃ§o e fim, nÃºmero do vagÃ£o e regiÃ£o que vamos analisar

In [4]:
num_train = 4306

DateStart = datetime.strptime('20131121', '%Y%m%d')
DateEnd = datetime.strptime('20140501', '%Y%m%d')
region_given = 2
#direction_given = 2
#sensor_num_given = 5

## Carregando os DataFrames

In [5]:
df_gps = load_Data_Frame_gps(num_train, region_given, DateStart, DateEnd)
df_gps

,Date,Daily_passing,Region,Direction,Longitude,Latitude,Altitude,Velocidade,TimeStamp
0,2014-01-10,4.0,2.0,1.0,-79.996248,40.436207,223.1,44.3,735601.929249
1,2014-01-10,4.0,2.0,1.0,-79.996300,40.436293,227.5,46.4,735601.929261
2,2014-01-10,4.0,2.0,1.0,-79.996170,40.436095,222.8,43.1,735601.929272
3,2014-01-10,4.0,2.0,1.0,-79.996065,40.435952,224.1,42.1,735601.929282
4,2014-01-10,4.0,2.0,1.0,-79.996195,40.435830,224.4,40.1,735601.929294
...,...,...,...,...,...,...,...,...,...
36674,2014-01-10,3.0,2.0,2.0,-79.995558,40.436973,232.6,15.5,735601.555706
36675,2014-01-10,3.0,2.0,2.0,-79.995538,40.437008,232.6,15.5,735601.555718
36676,2014-01-10,3.0,2.0,2.0,-79.995517,40.437045,232.6,15.5,735601.555729
36677,2014-01-10,3.0,2.0,2.0,-79.995497,40.437080,232.5,15.5,735601.555741
36678,2014-01-10,3.0,2.0,2.0,-79.995475,40.437115,232.5,15.5,735601.555752

In [8]:
df_gps.to_csv('df_gps.csv', index=False)

In [9]:
df_gps.groupby('Date').count()

,Daily_passing,Region,Direction,Longitude,Latitude,Altitude,Velocidade,TimeStamp
Date,,,,,,,,
2013-11-21,1200,1200,1200,1200,1200,1200,1200,1200
2013-12-27,2645,2645,2645,2645,2645,2645,2645,2645
2014-01-10,7926,7926,7926,7926,7926,7926,7926,7926
2014-01-24,1173,1173,1173,1173,1173,1173,1173,1173
2014-02-21,1258,1258,1258,1258,1258,1258,1258,1258
2014-03-14,127,127,127,127,127,127,127,127
2014-04-04,2382,2382,2382,2382,2382,2382,2382,2382
2014-04-11,7076,7076,7076,7076,7076,7076,7076,7076
2014-04-18,5832,5832,5832,5832,5832,5832,5832,5832
2014-04-25,7060,7060,7060,7060,7060,7060,7060,7060

In [10]:
df_acc = load_Data_Frame_acc(num_train, region_given, DateStart, DateEnd)
df_acc

,Date,Daily_passing,Region,Direction,Triaxial_x,Triaxial_y,Triaxial_z,Front_cab_uni,Back_cab_uni
0,2014-01-10,4.0,2.0,1.0,0.004539,NaN,NaN,NaN,NaN
1,2014-01-10,4.0,2.0,1.0,0.004606,NaN,NaN,NaN,NaN
2,2014-01-10,4.0,2.0,1.0,0.000596,NaN,NaN,NaN,NaN
3,2014-01-10,4.0,2.0,1.0,0.008501,NaN,NaN,NaN,NaN
4,2014-01-10,4.0,2.0,1.0,-0.001642,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...
219164258,2013-11-21,1.0,2.0,1.0,0.000700,0.000643,0.985388,0.0044,0.012329
219164259,2013-11-21,1.0,2.0,1.0,0.000700,0.000643,1.121367,0.0044,0.012329
219164260,2013-11-21,1.0,2.0,1.0,0.000700,0.000643,1.069745,0.0044,0.012329
219164261,2013-11-21,1.0,2.0,1.0,0.000700,0.000643,0.846696,0.0044,0.012329
219164262,2013-11-21,1.0,2.0,1.0,0.000700,0.000643,-0.022447,0.0044,0.012329

In [11]:
df_acc.to_csv('df_acc.csv', index=False)

In [ ]:
df_acc.groupby('Date').count()

In [ ]:
df_acc.isna().sum()